services:
  backend:
    build: ./backend
    container_name: vue-tetris-backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    container_name: vue-tetris-frontend
    ports:
      - "80:80"
